config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#show'
  resource :map, only: :show
  resources :crimes, only: [:new, :show, :index, :create]
  
  namespace :help do
    get :categorias
    get :sobre_nosotros 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crime.rb
class Crime < ApplicationRecord
  geocoded_by :address
  reverse_geocoded_by :lat, :long

  CRIME_CATEGORIES = {
    carro_robado: 'Carro robado',
    carro_robado_con_fuerza: 'Carro robado con fuerza',
    robo_a_carro: 'Robo a objetos en carro',
    asalto: 'Asalto',
    robo_con_fuerza: 'Robo forzado',
    hurto: 'Robo sin violencia',
    asalto_a_casa: 'Asalto a casa',
    robo_a_casa: 'Robo a casa',
    extorsion: 'Extorsión',
    asesinato: 'Asesinato',
    violacion: 'Violación',
    acoso: 'Acoso',
    acoso_sexual: 'Acoso sexual',
    secuestro: 'Secuestro'
  }.freeze

  REPORTER_VICTIM_RELATIOnSHIP_CATEGORIES = {
    self: 'Yo mismo',
    immediate_family: 'Familiar inmediato',
    extended_family: 'Familiar extendido',
    friend: 'Amigo o conocido inmediato',
    other: 'Otro'
  }.freeze
  
  validates :category, inclusion: { in: CRIME_CATEGORIES.keys.map(&:to_s) }
  validates :reporter_victim_relationship_category, inclusion: { in: REPORTER_VICTIM_RELATIOnSHIP_CATEGORIES.keys.map(&:to_s) }
  validates :title, presence: true
  validates :happened_at, presence: true
  validates :address, presence: true
  validates :lat, presence: true
  validates :long, presence: true

  def category_human_readable
    CRIME_CATEGORIES[category.to_sym] || 'Otro'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_reporter_id_cookie

  def set_reporter_id_cookie 
    return if reporter_id.present?
    cookies.signed[:rid] = SecureRandom.uuid
  end

  def reporter_id
    cookies.signed[:rid]
  end
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  before_action :set_crime, only: %i[ show edit update destroy ]

  # GET /crimes or /crimes.json
  def index
    bb = params[:bb]
    if bb.present?
      @crimes = Crime.within_bounding_box(bb.split(',')).where(happened_at: 30.days.ago..Time.current)
    else
      respond_to do |format|
        format.html { redirect_to :root }
        format.json { @crimes = [] }
      end
    end
  end

  # GET /crimes/1 or /crimes/1.json
  def show
  end

  # GET /crimes/new
  def new
    @crime = Crime.new
  end

  # GET /crimes/1/edit
  def edit
  end

  # POST /crimes or /crimes.json
  def create
    @crime = Crime.new(crime_params)

    respond_to do |format|
      if verify_recaptcha(model: @crime) && @crime.save
        format.html { redirect_to @crime, notice: "Crime was successfully created." }
        format.json { render :show, status: :created, location: @crime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crimes/1 or /crimes/1.json
  def update
    respond_to do |format|
      if @crime.update(crime_params)
        format.html { redirect_to @crime, notice: "Crime was successfully updated." }
        format.json { render :show, status: :ok, location: @crime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crimes/1 or /crimes/1.json
  def destroy
    @crime.destroy
    respond_to do |format|
      format.html { redirect_to crimes_url, notice: "Crime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crime
      @crime = Crime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crime_params
      params.require(:crime).permit(
        :category, 
        :title, 
        :description, 
        :happened_at, 
        :address, 
        :address_reference,
        :lat,
        :long,
        :reporter_victim_relationship_category
      ).merge(
        reporter_ip: request.remote_ip,
        reporter_user_agent: request.headers['User-Agent'],
        reporter_id: reporter_id
      )
    end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
    def categorias
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /crimes/1 or /crimes/1.json
  def show
    @location = request.location

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_ip_reverse_geocode
    lat = if_not_zero(request.location.latitude, otherwise: '14.592890948')
    long = if_not_zero(request.location.longitude, otherwise: '-90.49528645')
    hidden_field_tag("ip_reverse_geocode_lat", lat) + 
      hidden_field_tag("ip_reverse_geocode_long", long)
  end

  def if_not_zero(value, otherwise:)
    return value unless value.zero?
    otherwise
  end
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/views/crimes/_form.html.erb
<%= form_with(model: crime, class: 'form') do |form| %>
  <% if crime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crime.errors.count, "error") %> en el reporte:</h2>

      <ul>
        <% crime.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field bg-light">
    <%= form.label :category do %>
      Tipo de crimen 
      <a href="<%= help_categorias_path %>" target="_blank">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
        </svg>
      </a>
    <% end %>
    <%= form.select :category, options_for_select([['Seleccione', '']] + Crime::CRIME_CATEGORIES.invert.to_a.sort_by(&:first), '') %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :happened_at %>
    <%= form.datetime_field :happened_at %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :address_reference %>
    <%= form.text_field :address_reference %>
  </div>
  
  <div class="field">
    <%= form.label :reporter_victim_relationship_category %>
    <%= form.select :reporter_victim_relationship_category, options_for_select([['Seleccione', '']] + Crime::REPORTER_VICTIM_RELATIOnSHIP_CATEGORIES.invert.to_a, '') %>
  </div>

  <div class="field">
    <%= label_tag 'Posición en el mapa' %>
    <div id="mini-map"></div>
    <%= form.hidden_field :lat, id: 'crime-lat' %>
    <%= form.hidden_field :long, id: 'crime-long' %>
  </div>
  
  <div class="field">
    <%= recaptcha_tags %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crimes/edit.html.erb
<h1>Editing Crime</h1>

<%= render 'form', crime: @crime %>

<%= link_to 'Show', @crime %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crimes</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th>Happened at</th>
      <th>Address</th>
      <th>Address reference</th>
      <th>Reporter ip</th>
      <th>Reporter user agent</th>
      <th>Reporter</th>
      <th>Reporter victim relationship category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crimes.each do |crime| %>
      <tr>
        <td><%= crime.category %></td>
        <td><%= crime.title %></td>
        <td><%= crime.description %></td>
        <td><%= crime.happened_at %></td>
        <td><%= crime.address %></td>
        <td><%= crime.address_reference %></td>
        <td><%= crime.reporter_ip %></td>
        <td><%= crime.reporter_user_agent %></td>
        <td><%= crime.reporter_id %></td>
        <td><%= crime.reporter_victim_relationship_category %></td>
        <td><%= link_to 'Show', crime %></td>
        <td><%= link_to 'Edit', edit_crime_path(crime) %></td>
        <td><%= link_to 'Destroy', crime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="map" style="width: 100%; height: 400px"></div>
<br>

<style>
 .ol-popup {
        position: absolute;
        background-color: white;
        box-shadow: 0 1px 4px rgba(0,0,0,0.2);
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #cccccc;
        bottom: 12px;
        left: -50px;
        min-width: 280px;
      }
      .ol-popup:after, .ol-popup:before {
        top: 100%;
        border: solid transparent;
        content: " ";
        height: 0;
        width: 0;
        position: absolute;
        pointer-events: none;
      }
      .ol-popup:after {
        border-top-color: white;
        border-width: 10px;
        left: 48px;
        margin-left: -10px;
      }
      .ol-popup:before {
        border-top-color: #cccccc;
        border-width: 11px;
        left: 48px;
        margin-left: -11px;
      }
      .ol-popup-closer {
        text-decoration: none;
        position: absolute;
        top: 2px;
        right: 8px;
      }
      .ol-popup-closer:after {
        content: "✖";
      }
</style>

<div id="popup" class="ol-popup">
  <a href="#" id="popup-closer" class="ol-popup-closer"></a>
  <div id="popup-content"></div>
</div>

<%= link_to 'New Crime', new_crime_path %>

app/views/crimes/new.html.erb
<div class='form-container'>
    <h1>Reportar Nuevo Crimen</h1>

    <%= render_ip_reverse_geocode %>

    <%= render 'form', crime: @crime %>

    <%= link_to 'Regresar', :root %>
</div>

app/views/crimes/show.html.erb
<div class="info-container">
  <p id="notice"><%= notice %></p>

  <h1><%= @crime.category_human_readable %>: <%= @crime.title %></h1>

  <div class="info-box-container">
    <div class="crime-datetime info-box">
      <p><%= l @crime.happened_at, format: '%e de %B %Y' %></p>
      <p><%= l @crime.happened_at, format: '%A %l:%M%p' %></p>
    </div>

    <div class="crime-address info-box">
      <p>
        <%= @crime.address %>
      </p>

      <p>
        <%= @crime.address_reference %>
      </p>
    </div>
  </div>

  <p class="crime-description">
    <%= @crime.description %>
  </p>

  <iframe 
    width="100%" 
    height="400" 
    style="border:0" 
    loading="lazy" 
    allowfullscreen 
    src="https://www.google.com/maps/embed/v1/place?q=<%= @crime.lat %>%2C%20<%=@crime.long%>&key=AIzaSyBbioZBqAxk2_4WLMpHv9Vt8Yp700TWgKQ"
  ></iframe>

  <%= link_to 'Regresar', :root %>
</div>

app/views/help/categorias.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col bg-light p-3 m-mda-3 px-md-5">
            <h1>Categorías de crímenes</h1>

            <p>
                Hay muchas formas de categorizar los crímenes. Esta es una guía para ayudarte a escoger 
                la categoría más adecuada para el crimen que deseas reportar.
            </p>

            <h2>Crímenes contra la propiedad</h2>
            <dl class="row">
                <dt class="col-sm-3">Carro robado</dt>
                <dd class="col-sm-9">
                    Cuando el carro es robado sin ninguna interacción con el delincuente. Por ejemplo: 
                    el carro se dejó en un parqueo y al regresar ya no está.
                </dd>

                <dt class="col-sm-3">Carro robado con fuerza</dt>
                <dd class="col-sm-9">
                    Cuando el carro es robado por un delincuente que amenaza a la víctima. Por ejemplo:
                    el delincuente tiene un arma con la cual amenaza a la víctima para despojarla del carro.
                </dd>

                <dt class="col-sm-3">Robo a objetos en carro</dt>
                <dd class="col-sm-9">
                    Cuando objetos dentro del carro son sustraídos sin interacción con el delincuente.
                    Por ejemplo: una laptop es sustraída de un vehículo que está parqueado en la calle.
                </dd>

                <dt class="col-sm-3">Asalto</dt>
                <dd class="col-sm-9">
                    Robo o intento de robo a la propiedad en una persona con uso de armas. Por ejemplo:
                    Un delincuente roba la bolsa de una víctima con una pistola.
                </dd>

                <dt class="col-sm-3">Robo forzado</dt>
                <dd class="col-sm-9">
                    Robo o intento de robo a la propiedad en una persona con uso de fuerza. Por ejemplo:
                    un delincuente roba una bolsa de la víctima arrancándola por la fuerza.
                </dd>

                <dt class="col-sm-3">Robo sin fuerza</dt>
                <dd class="col-sm-9">
                    Robo o intento de robo a la propiedad de una persona sin el uso de fuerza. Por ejemplo:
                    un delincuente roba el celular dentro de una bolsa mientras la víctima está distraída.
                </dd>

                <dt class="col-sm-3">Asalto a casa</dt>
                <dd class="col-sm-9">
                    Cuando el delincuente roba o intenta robar objetos de una casa con uso de armas. Por ejemplo:
                    Delincuente utiliza pistola para amenazar a los ocupantes de una casa y forzar su ingreso.
                </dd>

                <dt class="col-sm-3">Robo a casa</dt>
                <dd class="col-sm-9">
                    Cuando el delincuente roba o intenta robar objetos en una casa sin uso de armas. Por ejemplo:
                    Delincuente salta una pared y roba una bicicleta del jardín sin interactuar con ningún ocupante.
                </dd>

                <dt class="col-sm-3">Extorsión</dt>
                <dd class="col-sm-9">
                    Cuando el delincuente obliga a la víctima con amenaza de violencia o intimidación a entregar su patrimonio.
                    Por ejemplo: un marero amenaza a un comerciante con un pago de "seguridad".
                </dd>
            </dl>

            <h2>Crímenes contra personas</h2>

            <dl class="row">
                <dt class="col-sm-3">Asesinato</dt>
                <dd class="col-sm-9">
                    Cuando hay una víctima mortal del crimen, incluso si el acto inicial era otro. Por ejemplo:
                    En un intento de robo, la víctima se opone y el delincuente dispara y mata a la víctima.
                </dd>

                <dt class="col-sm-3">Violación</dt>
                <dd class="col-sm-9">
                    Consiste en tener relaciones sexuales con una persona sin su consentimiento o con un 
                    consentimiento obtenido mediante la violencia o la amenaza.
                </dd>

                <dt class="col-sm-3">Acoso</dt>
                <dd class="col-sm-9">
                    Consiste en que una persona acecha y molesta a otra insistentemente perturbando su vida diaria y su libertad.
                </dd>

                <dt class="col-sm-3">Acoso sexual</dt>
                <dd class="col-sm-9">
                    Intimidación o acoso de naturaleza sexual, promesas no deseadas o inapropiadas a cambio de favores sexuales.
                </dd>

                <dt class="col-sm-3">Secuestro</dt>
                <dd class="col-sm-9">
                    Privación de libertad a la víctima, exigiendo, a cambio de su liberación, el cumplimiento de alguna condición.
                    Por ejemplo: el delincuente contacta a la familia de la víctima para coordinar un pago a cambio de su liberación.
                </dd>
            </dl>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crimenes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav id="a_header" class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to 'crimenes.gt', :root, class: "navbar-brand" %>
        <button class="navbar-toggler p-0 border-0" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Reportar crimen', new_crime_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sobre nosotros', help_sobre_nosotros_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <section id="content">
      <%= yield %>
    </section>
  </body>
</html>

app/views/maps/show.html.erb
<div id="map-container">
    <%= render_ip_reverse_geocode %>
    <div id="map"></div>

    <div id="popup" class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer"></a>
        <div id="popup-content">
            <div id="popup-title">
            </div>
            <%= link_to 'Más detalles >', crime_path(1), id: 'popup-link' %>
        </div>
    </div>

    <%= link_to '+', new_crime_path, class: "new-crime" %>
</div>